#!/bin/bash

if [[ $# != 1 ]]; then
	exit 1
fi

if [ ! -f auth.key ]; then
	echo -n "Enter tempest Auth key: "
	read authKey

	echo $authKey > auth.key
fi
chmod 700 postgres

rm -rf postgres/*/.gitignore
rm -rf postgres/pg_logical/snapshots/.gitignore

if [[ $1 == 'pi' || $1 == 'arm' ]]; then
	docker pull codyp424/tempest.pi
fi

if [[ $1 == 'x86' ]]; then
	docker image import container/container.tar dev:debian
fi


docker run -it -v $(pwd):/proj -v $(pwd)/postgres:/var/lib/postgresql/11/main -p 5432:5432 codyp424/tempest.pi /bin/bash -c "chown -R postgres:postgres /var/lib/postgresql/11/main ;pg_ctlcluster 11 main start; python /proj/connector/main.py --backfillAll"
