#!/bin/bash

if [[ $# != 1 ]]; then
	exit 1
fi

echo -n "Enter tempest Auth key: "
read authKey

echo $authKey > auth.key



if [[ $1 == 'pi' || $1 == 'arm' ]]; then
	docker pull codyp424/tempest.pi
fi

if [[ $1 == 'x86' ]]; then
	docker image import container/container.tar dev:debian
fi


docker run -it -v $(pwd):/proj -v $(pwd)/postgres:/var/lib/postgresql/11/main -p 5432:5432 codyp424/tempest.pi /bin/bash -c "chown -R postgres:postgres /var/lib/postgresql/11/main ;pg_ctlcluster 11 main start; python /proj/connector/main.py --backfillAll"
