#!/bin/bash
echo $(pwd)
docker run -d -v $(pwd):/proj -v $(pwd)/postgres:/var/lib/postgresql/11/main -p 5432:5432 codyp424/tempest.pi /bin/bash -c "chown -R postgres:postgres /var/lib/postgresql/11/main ;pg_ctlcluster 11 main start;service cron start; python /proj/connector/main.py --backfill; tail -f /dev/null"
